### ISSUE TITLE
Wire portable leaves an empty folder in appdata

### ISSUE THREAD

**Issue by sakibarifin** [portapps/wire-portable#5]
#### Steps to reproduce this issue

1. Run the program
2. It creates "C:\Users\user\AppData\Roaming\Wire\logs"
3. The folder exists even if the app is closed

#### Expected behaviour

> The folder shouldn't stay as a leftover

### Configuration

**App release** : Latest version - 3.11.3259

**Operating system** : Windows 10 Pro 64 bits

**Comment by crazy-max** [comment]
@sakibarifin This has been fixed through an opt-in `cleanup` config parameter. See Configuration section in https://portapps.io/app/wire-portable/#infos for more info.
